// @ts-check
import { defineConfig } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';

// Redirects for the ~225 old-site blog/utility URLs that don't get their own
// page on the rebuilt site (see docs/11-REDIRECTS-GAPFILL.md for the tiering
// and rationale, docs/seo/blog-redirect-proposal-2026-09-11.csv for the raw
// data this was generated from). Astro emits these as static redirect pages
// on `output: 'static'` (no adapter configured yet) -- if/when a host is
// confirmed (Vercel per CLAUDE.md, unconfirmed), port this same map into
// that host's native redirect config for true HTTP 301s. A Netlify-format
// `public/_redirects` file with the identical rules ships alongside this as
// a fallback in case Netlify ends up being the host instead.
//
// Tier B (13 posts) is NOT in this map -- pending a content strategy, see
// docs/12-BLOG-TIER-B-STRATEGY.md.
//
// Tier A update (2026-09-11): the 18 real Tier A posts (2 more were rejected
// on content-governance grounds and 3 are confirmed gone from the live site
// -- see docs/11-REDIRECTS-GAPFILL.md) were originally kept live at their
// exact old root-level URLs specifically to preserve real backlink equity
// (BuzzFeed, Vanity Fair, Daily Mail links, plus GSC ranking history). The
// client explicitly asked to move them under /blog/{slug}/ instead, for
// URL-structure consistency with the new blog system -- see
// src/content.config.ts and src/pages/blog/. The 18 redirects below trade
// some of that backlink equity for that consistency; this is a deliberate,
// requested reversal of the earlier decision, not an oversight.
const tierAMigrationRedirects = {
  "/toxic-codependency-looks-like/": "/blog/toxic-codependency-looks-like/",
  "/sex-addiction-drug-addiction/": "/blog/sex-addiction-drug-addiction/",
  "/vicious-cycle-addiction/": "/blog/vicious-cycle-addiction/",
  "/mackenzie-phillips-joins-breathe-as-addiction-counselor/": "/blog/mackenzie-phillips-joins-breathe-as-addiction-counselor/",
  "/5-weird-things-alcohol-withdrawal/": "/blog/5-weird-things-alcohol-withdrawal/",
  "/hookah-smoking-smoking-tobacco/": "/blog/hookah-smoking-smoking-tobacco/",
  "/can-you-force-someone-to-go-to-rehab/": "/blog/can-you-force-someone-to-go-to-rehab/",
  "/abuse-c-ptsd-complex-post-traumatic-stress-disorder/": "/blog/abuse-c-ptsd-complex-post-traumatic-stress-disorder/",
  "/smoking-suicide/": "/blog/smoking-suicide/",
  "/prevent-failure-launch-children/": "/blog/prevent-failure-launch-children/",
  "/skillful-vs-unskillful-love/": "/blog/skillful-vs-unskillful-love/",
  "/psychiatrist-steve-karp/": "/blog/psychiatrist-steve-karp/",
  "/how-to-start-the-conversation-about-rehab/": "/blog/how-to-start-the-conversation-about-rehab/",
  "/breathes-new-office-location-on-melrose/": "/blog/breathes-new-office-location-on-melrose/",
  "/manage-nicotine-withdrawal/": "/blog/manage-nicotine-withdrawal/",
  "/living-with-someone-who-has-ocd/": "/blog/living-with-someone-who-has-ocd/",
  "/orange-new-black-got-mackenzie-phillips-tap-past/": "/blog/orange-new-black-got-mackenzie-phillips-tap-past/",
  "/flight-attendant-mental-health/": "/blog/flight-attendant-mental-health/",
};

const redirects = {
  ...tierAMigrationRedirects,
  "/4-ways-to-heal-from-psychological-trauma/": "/conditions/complex-trauma/",
  "/5-absolute-important-steps-take-relapse/": "/programs/alumni-program/",
  "/5-things-cheaper-drug-screening/": "/",
  "/7-signs-of-depression/": "/conditions/depression/",
  "/7-signs-you-are-suffering-from-anorexia/": "/what-we-treat/eating-disorders/",
  "/7-triggering-situations-recovering-addicts-avoid/": "/",
  "/a-cut-above/": "/",
  "/addicted-alcohol-problem/": "/what-we-treat/alcohol/",
  "/addicted-food-journey-recovery/": "/",
  "/addiction-myths-vs-facts/": "/",
  "/addiction-treatment-center-best-option-2/": "/",
  "/addiction-treatment-west-hollywood/": "/",
  "/advantages-alcohol-support-groups/": "/what-we-treat/alcohol/",
  "/affordable-care-act-provides-access-to-treatment/": "/",
  "/alcohol-anxiety-navigating-dual-diagnosis-treatment-in-west-hollywood/": "/what-we-treat/alcohol/",
  "/alcohol-awareness-month-for-the-health-of-it/": "/what-we-treat/alcohol/",
  "/alcohol-drug-addiction-treatment/": "/what-we-treat/alcohol/",
  "/alliance-with-experience-recovery/": "/",
  "/alumni-support/": "/",
  "/anorexia-treatment-los-angeles/": "/what-we-treat/eating-disorders/",
  "/anorexia-versus-bulimia/": "/what-we-treat/eating-disorders/",
  "/anorexia/": "/what-we-treat/eating-disorders/",
  "/aspartame-calorie-cost/": "/",
  "/bed-the-most-common-eating-disorder-in-america/": "/what-we-treat/eating-disorders/",
  "/benefits-group-therapy-addiction/": "/",
  "/benefits-of-depression-screening/": "/conditions/depression/",
  "/benefits-quitting-smoking/": "/what-we-treat/",
  "/best-anger-management-strategies/": "/",
  "/binge-eating-disorder-treatment/": "/what-we-treat/eating-disorders/",
  "/binge-eating-disorder/": "/what-we-treat/eating-disorders/",
  "/body-dysmorphia-disorder/": "/what-we-treat/eating-disorders/",
  "/body-dysmorphic-disorder-causes/": "/what-we-treat/eating-disorders/",
  "/body-dysmorphic-disorder-symptoms/": "/what-we-treat/eating-disorders/",
  "/body-dysmorphic-disorder-treatment/": "/what-we-treat/eating-disorders/",
  "/breathe-awarded-accreditation-joint-commission/": "/about/",
  "/breathe-eating-disorder-recovery/": "/what-we-treat/eating-disorders/",
  "/breathe-life-healing-centers-employment-application/": "/resources/media/",
  "/breathe-weho-treatment-services-earns-joint-commissions-gold-seal-approval/": "/about/",
  "/breeding-addiction-moms-babies-opiates-arrive-pre-loaded/": "/what-we-treat/opioids/",
  "/bulimia-causes/": "/what-we-treat/eating-disorders/",
  "/bulimia-treatment-in-los-angeles-pathways-to-a-healthier-you/": "/what-we-treat/eating-disorders/",
  "/bulimia/": "/what-we-treat/eating-disorders/",
  "/bullying-battle-cry-its-no-joke/": "/",
  "/caffeine-overdose/": "/",
  "/can-you-ever-fully-recover-from-an-eating-disorder/": "/what-we-treat/eating-disorders/",
  "/cape-bowl/": "/",
  "/cheers-health/": "/",
  "/chemsex-crystal-meth-navigating-recovery-in-west-hollywood/": "/what-we-treat/methamphetamine/",
  "/clinical-outreach-coordinator/": "/resources/media/",
  "/common-eating-disorder-america/": "/what-we-treat/eating-disorders/",
  "/coping-patterns-in-complex-trauma-and-addiction/": "/conditions/complex-trauma/",
  "/coping-vs-avoiding-pain/": "/",
  "/could-you-unknowingly-have-an-eating-disorder/": "/what-we-treat/eating-disorders/",
  "/crystal-meth-addiction-treatment-in-los-angeles/": "/what-we-treat/methamphetamine/",
  "/day-treatment/": "/programs/php/",
  "/dealing-with-early-sobriety-triggers/": "/",
  "/depression-and-addiction/": "/conditions/depression/",
  "/depression-in-college-students/": "/conditions/depression/",
  "/detox-increase-quit/": "/programs/medical-detox/",
  "/digital-edit/": "/",
  "/do-i-have-complex-trauma/": "/conditions/complex-trauma/",
  "/dr-tian-dayton/": "/resources/media/",
  "/drinking-back-years/": "/",
  "/drug-addicts-anonymous-meetings-expect/": "/programs/alumni-program/",
  "/drug-dealer-co-pay/": "/",
  "/drugs-in-the-digital-age/": "/",
  "/dual-diagnosis-relationship-substance-abuse-mental-illness/": "/conditions/dual-diagnosis/",
  "/dual-diagnosis-substance-abuse-and-mental-illness/": "/conditions/dual-diagnosis/",
  "/dual-diagnosis-treatment-program/": "/conditions/dual-diagnosis/",
  "/dude-wheres-my-car/": "/",
  "/educated-eating-diets-designed-fail-2/": "/",
  "/experience-detox-residential/": "/programs/medical-detox/",
  "/failure-to-launch/": "/",
  "/faq/": "/",
  "/fighting-depression-in-the-summer/": "/conditions/depression/",
  "/finding-freedom-through-the-dance-of-liberation/": "/",
  "/fitness-rx-fun-matters/": "/",
  "/five-alive-qa-with-jed-hastings/": "/resources/media/",
  "/food-addiction-in-america/": "/what-we-treat/eating-disorders/",
  "/food-addiction-treatment/": "/what-we-treat/eating-disorders/",
  "/for-many-veterans-accidental-addiction-from-drugs-meant-to-heal/": "/",
  "/freedom-from-bondage/": "/",
  "/from-detox-to-recovery-in-los-angeles-the-role-of-addiction-treatment-centers/": "/programs/medical-detox/",
  "/from-survival-mode-to-stability-how-the-body-heals-in-treatment/": "/",
  "/good-golly-molly/": "/",
  "/guns-mental-illness-deadly-combination/": "/",
  "/he-intervenes-with-compassion/": "/resources/media/",
  "/healing-experiential-therapies/": "/",
  "/help-someone-with-anorexia/": "/what-we-treat/eating-disorders/",
  "/helping-the-addict-healing-the-family/": "/admissions/for-families/",
  "/heroin-breakthrough-need-money/": "/what-we-treat/opioids/",
  "/heroin-deaths-twice-bad/": "/what-we-treat/opioids/",
  "/heroin-pandemic-help-horizon/": "/what-we-treat/opioids/",
  "/heroin-the-drug-of-nice-suburban-areas/": "/what-we-treat/opioids/",
  "/history-removes-mystery/": "/",
  "/hit-snooze-button-taking-nap-always-lazy/": "/",
  "/holistic-approach-health-wellbeing/": "/",
  "/how-anorexia-affects-the-body/": "/what-we-treat/eating-disorders/",
  "/how-breathe-life-healing-centers-in-los-angeles-supports-long-term-sobriety-after-detox/": "/programs/medical-detox/",
  "/how-complex-trauma-impacts-our-sense-of-self-safety/": "/conditions/complex-trauma/",
  "/how-families-can-support-a-loved-one-in-addiction-treatment/": "/admissions/for-families/",
  "/how-methamphetamine-affects-your-physical-health/": "/what-we-treat/methamphetamine/",
  "/how-our-residential-rehab-can-help-you/": "/programs/residential-treatment/",
  "/how-to-be-the-sober-life-of-the-party/": "/",
  "/how-to-choose-the-right-drug-detox-center-in-los-angeles/": "/programs/medical-detox/",
  "/how-to-know-when-the-occasional-binge-turns-into-binge-eating-disorder/": "/what-we-treat/eating-disorders/",
  "/how-to-prevent-obesity/": "/what-we-treat/eating-disorders/",
  "/https-breathelifehealingcenters-com-embarrassing-things-binge-eating-disorder/": "/what-we-treat/eating-disorders/",
  "/https-breathelifehealingcenters-com-pill-popping-dermatologist/": "/",
  "/https-breathelifehealingcenters-com-time-to-give-back-tis-the-season-to-think-of-others/": "/",
  "/im-not-big-why-we-loathe-to-admit-it/": "/",
  "/importance-integrated-treatment-dual-diagnosis/": "/conditions/dual-diagnosis/",
  "/inpatient-mental-health-treatment/": "/",
  "/intensive-outpatient-program/": "/programs/intensive-outpatient/",
  "/internal-family-systems-and-its-role-in-restoring-balance/": "/",
  "/interventionist-brad-lamm-shares-his-insight-on-food-addiction/": "/what-we-treat/eating-disorders/",
  "/is-it-paranoia-or-psychosis-managing-meth-induced-mental-health-crises/": "/what-we-treat/methamphetamine/",
  "/joint-commission/": "/about/",
  "/josh-duggars-rehab-welcome-to-the-dark-ages/": "/",
  "/junior-high-marijuana-teens/": "/",
  "/laugh-way-joyful-life/": "/",
  "/lifesaver-youve-never-heard/": "/",
  "/light-life/": "/",
  "/look-for-drug-intervention-specialist/": "/admissions/for-families/",
  "/los-angeles-holistic-recovery-overcoij-ming-fentanyl-and-kratom-addiction-beyond-detox/": "/what-we-treat/opioids/",
  "/love-addict-love-avoidant-a-match-made-in-hell/": "/",
  "/mackenzie-phillips-featured-on-fox-11-los-angeles/": "/resources/media/",
  "/mackenzie-phillips-joins-addiction-counselor/": "/resources/media/",
  "/man-weighed-530lbs-reveals-lost-half-body-weight/": "/",
  "/media-mania/": "/",
  "/medical-alcohol-and-drug-detox/": "/what-we-treat/alcohol/",
  "/medication-assisted-treatment-for-long-term-stability/": "/programs/medication-assisted-treatment/",
  "/medication-assisted-treatment-mat/": "/programs/medication-assisted-treatment/",
  "/medication-assisted-treatment/": "/programs/medication-assisted-treatment/",
  "/meet-the-intake-team/": "/resources/media/",
  "/melissa-mccracken-speaks-at-cma2020/": "/resources/media/",
  "/mental-health-awareness-month-b4stage4/": "/",
  "/mental-health-help-available/": "/",
  "/mental-health-treatment/": "/",
  "/meth-addiction-getting-help/": "/what-we-treat/methamphetamine/",
  "/meth-addiction-how-crystal-recovery-works/": "/what-we-treat/methamphetamine/",
  "/michael-phelps/": "/",
  "/moderate-drinking-really-safe-may-never-know/": "/",
  "/most-addictive-substances/": "/",
  "/motivators-western-diet/": "/what-we-treat/eating-disorders/",
  "/new-peer-pressure-hashtags-facebook-feeds/": "/",
  "/newsnight-debate-between-matthew-perry-and-peter-hitchens/": "/",
  "/nfl-suit-pain-meds/": "/what-we-treat/opioids/",
  "/numbing-the-pain-the-link-between-heroin-and-unresolved-trauma/": "/what-we-treat/opioids/",
  "/nyc-smoking-spikes/": "/what-we-treat/",
  "/obesity-the-world-is-literally-round/": "/what-we-treat/eating-disorders/",
  "/off-the-court-the-life-of-lamar-odom/": "/",
  "/one-year-anniversary/": "/resources/media/",
  "/overcome-alcohol-withdrawal/": "/what-we-treat/alcohol/",
  "/pain-meds-xanax-anxiety/": "/what-we-treat/opioids/",
  "/phillip-seymour-hoffman-dead-actor-dies-46/": "/",
  "/php-vs-iop-understanding-different-levels-of-addiction-treatment/": "/programs/intensive-outpatient/",
  "/post-acute-withdrawal-syndrome-in-los-angeles-managing-recovery-after-detox/": "/programs/medical-detox/",
  "/post-traumatic-stress-disorder-ptsd/": "/conditions/trauma/",
  "/professional-help-anxiety/": "/conditions/anxiety/",
  "/ptsd-and-substance-use-why-trauma-and-addiction-are-often-connected/": "/conditions/complex-trauma/",
  "/ptsd-treatment-in-los-angeles-integrating-trauma-therapy-with-addiction-recovery/": "/conditions/trauma/",
  "/reasons-rehab-2-prescription-medication-addiction/": "/",
  "/reckless-doctor-faces-justice/": "/",
  "/relapse-prone/": "/programs/alumni-program/",
  "/residential-treatment-for-substance-addiction/": "/programs/residential-treatment/",
  "/risks-of-untreated-adhd/": "/",
  "/robin-williams-fame-self-shame/": "/",
  "/rodrigo-dasilva-joins-the-breathe-team/": "/resources/media/",
  "/safe-from-self-harm/": "/",
  "/self-care-health-care/": "/",
  "/september-is-recovery-monthwhat-does-that-mean-really/": "/",
  "/sero-mental-health/": "/about/sero-mental-health/",
  "/service-for-sobriety-three-tools-for-making-it-stick/": "/",
  "/sleep-hygiene-tips/": "/",
  "/smoking-booze-get-outa-town/": "/what-we-treat/",
  "/sober-living-home-can-benefit-your-recovery/": "/programs/sober-living/",
  "/sobriety-on-pain-meds/": "/what-we-treat/opioids/",
  "/staying-sober-during-the-holidays/": "/",
  "/still-debating-naloxone-life-saving-emergency-drug/": "/",
  "/strategies-complex-trauma/": "/conditions/complex-trauma/",
  "/substance-free-summer-activities/": "/",
  "/sugar-blows/": "/",
  "/summer-eat-wave/": "/",
  "/support-groups-for-family-members-of-drug-addicts/": "/admissions/for-families/",
  "/teen-depression-symptoms-causes/": "/conditions/depression/",
  "/the-beauty-blueprint/": "/",
  "/the-good-food-mood/": "/",
  "/the-new-heroin-why-the-rules-of-recovery-have-changed/": "/what-we-treat/opioids/",
  "/the-new-world-what-christopher-columbus-can-teach-us-about-recovery/": "/",
  "/the-polyvagal-theory-trauma-and-mental-health/": "/conditions/complex-trauma/",
  "/the-rules-are-different/": "/",
  "/the-trajectory-of-addiction-to-recovery/": "/",
  "/the-whole-person-approach-why-holistic-alcohol-rehab-is-taking-over-los-angeles/": "/what-we-treat/alcohol/",
  "/things-need-know-trichotillomania/": "/what-we-treat/eating-disorders/",
  "/thinking-back/": "/",
  "/this-is-what-toxic-codependency-looks-like/": "/",
  "/tips-coping-eating-disorder-holidays/": "/what-we-treat/eating-disorders/",
  "/tips-parents-addicts/": "/admissions/for-families/",
  "/top-5-facts-and-myths-about-eating-disorders/": "/what-we-treat/eating-disorders/",
  "/toxic-codependent-looks-like/": "/",
  "/transitional-living-after-residential-treatment/": "/programs/residential-treatment/",
  "/trauma-and-addiction/": "/conditions/complex-trauma/",
  "/treatment-eating-disorders/": "/what-we-treat/eating-disorders/",
  "/treatment-for-bulimia/": "/what-we-treat/eating-disorders/",
  "/types-anxiety-disorder/": "/conditions/anxiety/",
  "/types-eating-disorders-explained/": "/what-we-treat/eating-disorders/",
  "/understanding-alcohol-withdrawal-symptoms-causes-and-treatment/": "/what-we-treat/alcohol/",
  "/vaping-illness-syndrome/": "/what-we-treat/",
  "/what-causes-anorexia/": "/what-we-treat/eating-disorders/",
  "/what-does-dual-diagnosis-mean/": "/conditions/dual-diagnosis/",
  "/what-happens-during-meth-detox/": "/what-we-treat/methamphetamine/",
  "/what-happens-to-your-body-and-mind-when-you-stop-using-meth-after-chemsex/": "/what-we-treat/methamphetamine/",
  "/what-is-anorexia/": "/what-we-treat/eating-disorders/",
  "/what-is-body-dysmorphic-disorder/": "/what-we-treat/eating-disorders/",
  "/what-is-bulimia/": "/what-we-treat/eating-disorders/",
  "/what-is-methamphetamine/": "/what-we-treat/methamphetamine/",
  "/what-is-obsessive-compulsive-disorder/": "/conditions/anxiety/",
  "/what-is-ocd/": "/conditions/anxiety/",
  "/what-is-trichotillomania/": "/what-we-treat/eating-disorders/",
  "/whats-even-in-diet-pills/": "/what-we-treat/eating-disorders/",
  "/when-its-time-to-tell-the-family-about-your-addiction/": "/",
  "/why-is-depression-on-the-rise/": "/conditions/depression/",
  "/world-intervention-day/": "/admissions/for-families/",
  "/you-dont-have-to-do-it-alone/": "/",
};

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [tailwindcss()]
  },
  redirects,
});
